### ISSUE TITLE
using org-ref html export for slides

### ISSUE THREAD

**Issue by ssfrr** [jkitchin/org-ref#604]
I've used [reveal.js](https://revealjs.com/#/) frequently to make slides, and am now trying to integrate it into my org-mode setup. If you're not familiar, the general idea is that you export HTML with some javascript that makes a nice slide deck.

It seems that org-ref HTML export is almost doing what I'd like, and the CSS classes make it easy to customize the appearance. I'm having 2 issues currently:

1. the key that shows up at the citation location is the full bibtex key - is there a way to make it just a number?
2. I'd like to have a separate bibliography list on each slide, but currently the bibliography that shows up has all the references for all the citations. Is there a way to "reset" the list of citations between each slide?

So far I have an input file:

```org
# -*- org-export-initial-scope: buffer; -*-
#+OPTIONS: num:nil toc:nil reveal_slide_number:c/t
#+OPTIONS: email:t date:t timestamp:nil
#+REVEAL_EXTRA_CSS: custom.css
#+REVEAL_TRANS: none
#+REVEAL_THEME: serif
#+Title: Music Source Separation
#+Author: Spencer Russell
#+Email: sfr@media.mit.edu
#+Date: Oct. 12, 2018

* Blind Source Separation (BSS)
* Localization
There's a great paper on localzation cite:makino_blind_2007.

bibliography:bibliography.bib

* Harmonic/Percussive Source Separation (HPSS)

Median filters can be used to separate harmonic from percussive content cite:fitzgerald_harmonic/percussive_2010.

bibliography:bibliography.bib
```

with a custom CSS (there's probably a better way to get rid of the "Bibliography" header):

```css
h1.org-ref-bib-h1 {
    font-size: 0;
    margin: 0;
}

ul.org-ref-bib {
    font-size: 0.4em;
    list-style-type: none;
}

a.org-ref-reference {
    vertical-align: super;
    font-size: 0.4em;
}
```

Which gives me (for one of the slides):

![image](https://user-images.githubusercontent.com/734386/46628642-2ecc7f00-cb0c-11e8-90a3-07e75344370b.png)
